export const CORTICO_DATA = {
  nodes: [
    { id: "Hypothalamus", group: "Master", val: 40 },
    { id: "Hypophyse", group: "Master", val: 30 },
    { id: "CRH", group: "Hormone", val: 25 },
    { id: "ACTH", group: "Hormone", val: 30 },
    { id: "Cortisol", group: "Hormone", val: 35 },
    { id: "DHEA", group: "Hormone", val: 20 },
    { id: "Aldostérone", group: "Hormone", val: 20 },
    { id: "Alpha_Sympathique", group: "Master", val: 30 },
    { id: "Adrénaline", group: "Hormone", val: 20 },
    { id: "Cortex_Surrenal", group: "Glande", val: 25 },
    { id: "Médullosurrénale", group: "Glande", val: 15 },
    { id: "Rein", group: "Glande", val: 15 },
    { id: "Foie", group: "Glande", val: 15 },
    { id: "Systeme_Immunitaire", group: "Systeme", val: 20 },
    { id: "ACTH_Alpha_MSH", group: "Hormone", val: 15 },
    { id: "Prolactine_PL", group: "Hormone", val: 15 },
    { id: "Vasopressine_AVP", group: "Hormone", val: 15 },
    { id: "Metabolisme_Glucose", group: "Symptome", val: 15 },
    { id: "Metabolisme_Lipides", group: "Symptome", val: 15 },
    { id: "Inflammation", group: "Symptome", val: 20 },
    { id: "Anxiété", group: "Symptome", val: 15 },
    { id: "Insomnie", group: "Symptome", val: 15 },
    { id: "Dépression", group: "Symptome", val: 15 },
    { id: "Hypoglycémie", group: "Symptome", val: 15 },
    { id: "Passiflora_incarnata", group: "Plante", val: 18 },
    { id: "Ribes_nigrum", group: "Plante", val: 18 },
    { id: "Rhodiola_rosea", group: "Plante", val: 18 },
    { id: "Eleutherococcus_senticosus", group: "Plante", val: 18 },
    { id: "Quercus_pedunculata", group: "Plante", val: 18 },
    { id: "Glycyrrhiza_glabra", group: "Plante", val: 18 }
  ],
  links: [
    { source: "Hypothalamus", target: "CRH", name: "Produit" },
    { source: "CRH", target: "ACTH", name: "Stimule" },
    { source: "CRH", target: "Hypophyse", name: "Stimule" },
    { source: "Hypophyse", target: "ACTH", name: "Produit" },
    { source: "ACTH", target: "Cortex_Surrenal", name: "Stimule" },
    { source: "ACTH", target: "DHEA", name: "Stimule" },
    { source: "ACTH", target: "Aldostérone", name: "Stimule" },
    { source: "Cortex_Surrenal", target: "Cortisol", name: "Produit" },
    { source: "Cortex_Surrenal", target: "DHEA", name: "Produit" },
    { source: "Cortex_Surrenal", target: "Aldostérone", name: "Produit" },
    { source: "Cortisol", target: "ACTH", name: "Rétrocontrôle (-)" },
    { source: "Cortisol", target: "CRH", name: "Rétrocontrôle (-)" },
    { source: "Alpha_Sympathique", target: "CRH", name: "Stimule" },
    { source: "Alpha_Sympathique", target: "ACTH", name: "Stimule" },
    { source: "Alpha_Sympathique", target: "Cortisol", name: "Stimule" },
    { source: "Alpha_Sympathique", target: "Médullosurrénale", name: "Stimule" },
    { source: "Médullosurrénale", target: "Adrénaline", name: "Produit" },
    { source: "ACTH", target: "ACTH_Alpha_MSH", name: "Produit" },
    { source: "ACTH_Alpha_MSH", target: "ACTH", name: "Stimule" },
    { source: "ACTH_Alpha_MSH", target: "Cortisol", name: "Stimule" },
    { source: "Vasopressine_AVP", target: "ACTH", name: "Stimule" },
    { source: "Prolactine_PL", target: "CRH", name: "Stimule" },
    { source: "Prolactine_PL", target: "ACTH", name: "Stimule" },
    { source: "Cortisol", target: "Systeme_Immunitaire", name: "Inhibe" },
    { source: "Cortisol", target: "Inflammation", name: "Inhibe" },
    { source: "Cortisol", target: "Metabolisme_Glucose", name: "Stimule" },
    { source: "Cortisol", target: "Metabolisme_Lipides", name: "Mobilise" },
    { source: "Cortisol", target: "Anxiété", name: "Provoque" },
    { source: "Cortisol", target: "Insomnie", name: "Provoque" },
    { source: "Cortisol", target: "Dépression", name: "Provoque" },
    { source: "Cortisol", target: "Hypoglycémie", name: "Régule (-)" },
    { source: "Aldostérone", target: "Rein", name: "Régule" },
    { source: "Cortisol", target: "Foie", name: "Mobilise" },
    { source: "Passiflora_incarnata", target: "Alpha_Sympathique", name: "Inhibe" },
    { source: "Passiflora_incarnata", target: "Cortisol", name: "Régule" },
    { source: "Ribes_nigrum", target: "Cortex_Surrenal", name: "Soutient" },
    { source: "Rhodiola_rosea", target: "Cortex_Surrenal", name: "Soutient" },
    { source: "Eleutherococcus_senticosus", target: "Cortex_Surrenal", name: "Soutient" },
    { source: "Quercus_pedunculata", target: "Cortex_Surrenal", name: "Soutient" },
    { source: "Glycyrrhiza_glabra", target: "Cortisol", name: "Améliore" }
  ]
};
